/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP DATABASE IF EXISTS `rpa_local`;
CREATE DATABASE IF NOT EXISTS `rpa_local` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `rpa_local`;

/*!40000 ALTER TABLE `feriados` DISABLE KEYS */;
INSERT INTO `feriados` (`id`, `fecha`) VALUES
	(1, '20210917'),
	(2, '20210918'),
	(3, '20210919'),
	(4, '20211011'),
	(5, '20211101'),
	(6, '20211201'),
	(7, '20220415'),
	(8, '20220416'),
	(9, '20220521'),
	(10, '20220621'),
	(11, '20220627'),
	(12, '20220815'),
	(13, '20220919'),
	(14, '20221010'),
	(15, '20221031'),
	(16, '20221101');
/*!40000 ALTER TABLE `feriados` ENABLE KEYS */;

/*!40000 ALTER TABLE `saludos` DISABLE KEYS */;
INSERT INTO `saludos` (`id`, `saludo`, `idioma`) VALUES
	(1, 'Buenos dias!', 'Español'),
	(2, 'Good Morning!', 'Inglés'),
	(3, 'Almáre’ arin', 'Quenya (lord of the rings)'),
	(4, 'Rewon lefpom', 'Na’vi (avatar)'),
	(5, 'leelas yinauk', 'Minionese (despicable me)'),
	(6, 'maj po', 'Klingon (star trek)'),
	(7, 'bonan matenon', 'Esperanto'),
	(8, 'Sanibonani', 'Zulu'),
	(9, 'E kaaro', 'Yoruba'),
	(10, 'gut margn', 'Yiddish'),
	(11, 'shalom!', 'Yiddish'),
	(12, 'Molweni', 'Xhosa'),
	(13, 'Mholo ngalentsasa', 'Xhosa'),
	(14, 'Bore da', 'Welsh'),
	(15, 'Chào buổi sáng', 'Vietnamese'),
	(16, 'Xayrli tong', 'Uzbek'),
	(17, 'صبح بخیر', 'Urdu'),
	(18, 'Dobre rano', 'Ukrainian'),
	(19, 'Dobroho ranku', 'Ukrainian'),
	(20, 'Günaydın', 'Turkish'),
	(21, 'Dumêla rra', 'Tswana'),
	(22, 'Dumêla mma', 'Tswana'),
	(23, 'Avuxeni', 'Tsonga'),
	(24, 'Avuxeni', 'Tsonga'),
	(25, 'Osda sunalei', 'Tsalagi Cherokee'),
	(26, 'Osda svnalei', 'Tsalagi Cherokee'),
	(27, 'nga-to delek', 'Tibetan'),
	(28, 'shokba delek', 'Tibetan'),
	(29, 'sà-wàt-dee kráp', 'Thai'),
	(30, 'sà-wàt-dee kâ', 'Thai'),
	(31, 'subhodayamu', 'Telugu'),
	(32, 'supra bhetam', 'Telugu'),
	(33, 'Xeyírlí irte', 'Tatar'),
	(34, 'Kālai vaṇakkam', 'Tamil'),
	(35, 'kaala vanakkã', 'Tamil'),
	(36, 'Subḩ ba xajr', 'Tajik'),
	(37, 'gau-tsa', 'Taiwanese Hokkien'),
	(38, '‘Ia ora na ‘oe', 'Tahitian'),
	(39, '‘Ia ora na ‘outou', 'Tahitian'),
	(40, 'Magandang umaga po', 'Tagalog Filipino'),
	(41, 'Magandang umaga', 'Tagalog Filipino'),
	(42, 'Guten Morgen', 'Swiss German'),
	(43, 'Grüezi', 'Swiss German'),
	(44, 'God morgon', 'Swedish'),
	(45, 'Sawubona', 'Swati'),
	(46, 'habari ya asubuhi', 'Swahili'),
	(47, 'Wilujeng enjing', 'Sundanese'),
	(48, 'Subax wanaagsan', 'Somali'),
	(49, 'Davra aena        ', 'Dothraki (Game of Thrones)'),
	(50, 'Dobro jutro', 'Slovenian'),
	(51, 'Dober dan', 'Slovenian'),
	(52, 'Dobré ráno', 'Slovak'),
	(53, 'Dobrý deň', 'Slovak'),
	(54, 'Suba Udesanak Wewa', 'Sinhala'),
	(55, 'Mangwanani akanaka', 'Shona'),
	(56, 'nóng zō', 'Shanghainese Wu'),
	(57, 'zōlǎng hō', 'Shanghainese Wu'),
	(58, 'zō ä', 'Shanghainese Wu'),
	(59, 'Dumela', 'Sesotho'),
	(60, 'Mmoro', 'Sesotho'),
	(61, 'Khotsong', 'Sesotho'),
	(62, 'Dobro utro', 'Serbian'),
	(63, 'Madainn mhath', 'Scots Gaelic'),
	(64, 'oa mai le ataeao', 'Samoan'),
	(65, 'Manuia le taeao', 'Samoan'),
	(66, 'Dobroye utro', 'Russian'),
	(67, 'Bună dimineața', 'Romanian'),
	(68, 'Sat Shri Akal', 'Punjabi'),
	(69, 'Bom dia', 'Portugese'),
	(70, 'Dzień dobry', 'Polish'),
	(71, 'Sahar de pa Khair', 'Pashto'),
	(72, 'Bon dia', 'Papiamento'),
	(73, 'Mòro', 'Papiamento'),
	(74, 'Akkam bultee', 'Oromo'),
	(75, 'ଶୁଭ ସକାଳ', 'Odia'),
	(76, 'God morgen', 'Norwegian'),
	(77, 'Thobela', 'Northern Sotho'),
	(78, 'Dumêlang', 'Northern Sotho'),
	(79, 'Mmorong', 'Northern Sotho'),
	(80, 'buongiorno', 'Neapolitan'),
	(81, 'bonnì', 'Neapolitan'),
	(82, 'namaste ', 'Nepali'),
	(83, 'subha prabhat', 'Nepali'),
	(84, 'Öglouny mend', 'Mongolian'),
	(85, 'Su-prabhat', 'Marathi'),
	(86, 'Ata mārie', 'Maori'),
	(87, 'Pai ata', 'Maori'),
	(88, 'Bongu', 'Maltese'),
	(89, 'L-għodwa t-tajba', 'Maltese'),
	(90, 'Bonġornu', 'Maltese'),
	(91, 'Suprabhatham', 'Malayalam'),
	(92, 'Selamat Pagi', 'Malay'),
	(93, 'Salama', 'Malagasy'),
	(94, 'Manahoana', 'Malagasy'),
	(95, 'Dobro utro', 'Macedonian'),
	(96, 'Wasuze otya nno', 'Luganda'),
	(97, 'Gudde Moien', 'Luxembourgish'),
	(98, 'Labas rytas', 'Lithuanian'),
	(99, 'Mbote', 'Lingala'),
	(100, 'Gojemörge', 'Limburgish'),
	(101, 'Labrīt', 'Latvian'),
	(102, 'Bonum mane', 'Latin'),
	(103, 'Quid agis mane', 'Latin'),
	(104, 'Arrun Suo Sdey', 'Lao'),
	(105, 'Kutmanduu tanyngyz menen', 'Kyrgyz'),
	(106, 'Beyanî baş', 'Kurdish'),
	(107, 'Spéde bi xer', 'Kurdish'),
	(108, 'annyeong hashimnikka', 'Korean'),
	(109, 'joh-eun achim', 'Korean'),
	(110, 'Qayırlı tañ', 'Kazakh'),
	(111, 'shubhodaya', 'Kannada'),
	(112, 'Gud mawnin', 'Jamaican Patois'),
	(113, 'Ohayō gozaimasu', 'Japanese'),
	(114, 'ohayō', 'Japanese'),
	(115, 'Buongiorno', 'Italian'),
	(116, 'Maidin mhaith', 'Irish'),
	(117, 'Dia dhuit ar maidin', 'Irish'),
	(118, 'Dia dhaoibh ar maidin ', 'Irish'),
	(119, 'Ublaahatkut', 'Inuktitut'),
	(120, 'Selamat pagi', 'Indonesian Bahasa'),
	(121, 'Góðan daginn', 'Icelandic'),
	(122, 'Góðan dag', 'Icelandic'),
	(123, 'Jó reggelt', 'Hungarian'),
	(124, 'Nukwang Talöngva', 'Hopi'),
	(125, 'Zoo thaum sawv ntxov', 'Hmong'),
	(126, 'shubh prabhaat', 'Hindi'),
	(127, 'namaste', 'Hindi'),
	(128, 'Shub Din', 'Hindi'),
	(129, 'Boker tov', 'Hebrew'),
	(130, 'Aloha kakahiaka', 'Hawaiian'),
	(131, 'Ina kwana', 'Hausa'),
	(132, 'Barka da safiya', 'Hausa'),
	(133, 'Bonjou', 'Haitian Creole'),
	(134, 'suprabhat', 'Gujarati'),
	(135, 'Kaliméra', 'Greek'),
	(136, 'Kaliméra sas', 'Greek'),
	(137, 'Kaliméra su', 'Greek'),
	(138, 'Guten Morgen', 'German'),
	(139, 'Dila mushwidobisa', 'Georgian'),
	(140, 'Goeie moarn', 'Frisian'),
	(141, 'Bonjour', 'French'),
	(142, 'bon matin', 'French'),
	(143, 'Goeije morn', 'Flemish'),
	(144, 'Hyvää huomenta', 'Finnish'),
	(145, 'Huomenta', 'Finnish'),
	(146, 'Ni sa yadra', 'Fijian'),
	(147, 'Yadra', 'Fijian'),
	(148, 'Sob Bekhair', 'Farsi '),
	(149, 'Salam', 'Farsi '),
	(150, 'Góðan morgun', 'Faroese'),
	(151, 'tere hommikust', 'Estonian'),
	(152, 'Goeie more', 'Afrikaans'),
	(153, 'More', 'Afrikaans'),
	(154, 'Mirëmëngjes', 'Albanian'),
	(155, 'əndämən addärk', 'Amharic'),
	(156, 'əndämən addärš', 'Amharic'),
	(157, 'əndämən addäru', 'Amharic'),
	(158, 'Sabah alkhyr', 'Arabic'),
	(159, 'Bari luys', 'Armenian'),
	(160, 'Paree looys', 'Armenian'),
	(161, 'xuprôbhat', 'Assamese'),
	(162, 'Sabahınız xeyir', 'Azerbaijani'),
	(163, 'Egun on', 'Basque'),
	(164, 'Guadn moing', 'Bavarian '),
	(165, 'Dobray ranici', 'Belarusian'),
	(166, 'Nomoskar', 'Bengali'),
	(167, 'Shu-probhaat', 'Bengali'),
	(168, 'Mwjang Fung', 'Bodo'),
	(169, 'Dobro jutro', 'Bosnian'),
	(170, 'Bom dia', 'Brazilian Portuguese'),
	(171, 'Demat', 'Breton'),
	(172, 'Dobro utro', 'Bulgarian'),
	(173, 'Mingalarba ', 'Burmese'),
	(174, '’ârŭn suŏ sdei', 'Cambodian Khmer'),
	(175, 'Bon dia', 'Catalan'),
	(176, 'M’mawa wabwino', 'Chichewa'),
	(177, 'Mwauka bwanji', 'Chichewa'),
	(178, 'jóusàhn ', 'Chinese Cantonese'),
	(179, 'zǎo’ān', 'Chinese Mandarin'),
	(180, 'zǎoshàng hǎo', 'Chinese Mandarin'),
	(181, 'zǎochén hǎo', 'Chinese Mandarin'),
	(182, 'nǐ zǎo ', 'Chinese Mandarin'),
	(183, 'Bonghjornu', 'Corsican'),
	(184, 'Dobro jutro', 'Croatian'),
	(185, 'dobré ráno', 'Czech'),
	(186, 'dobrý den', 'Czech'),
	(187, 'Godmorgen', 'Danish'),
	(188, 'Goedemorgen', 'Dutch'),
	(189, 'Dobro delek', 'Dzongkha Bhutanese'),
	(190, 'Chubo dele', 'Dzongkha Bhutanese');
/*!40000 ALTER TABLE `saludos` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
